/**
 * Sends a lead email notification via Resend REST API
 * @param {Object} lead - Sanitized lead data
 * @param {Object} env - Cloudflare Environment secrets
 * @returns {Promise<{success: boolean, messageId?: string, error?: string}>}
 */
export async function sendLeadEmail(lead, env) {
  const apiKey = env.EMAIL_API_KEY;
  const fromEmail = env.EMAIL_FROM;
  const toEmail = env.EMAIL_TO;

  if (!apiKey || !fromEmail || !toEmail) {
    console.error('[Email Helper] Missing email environment configurations.');
    return { success: false, error: 'Email configurations are missing on server.' };
  }

  const utmParams = [];
  if (lead.utm_source) utmParams.push(`Source: ${lead.utm_source}`);
  if (lead.utm_medium) utmParams.push(`Medium: ${lead.utm_medium}`);
  if (lead.utm_campaign) utmParams.push(`Campaign: ${lead.utm_campaign}`);
  const utmString = utmParams.length > 0 ? utmParams.join(', ') : 'None';

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>New Lead Captured</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #334155; margin: 0; padding: 0; }
        .wrapper { background-color: #f8fafc; padding: 32px 16px; }
        .card { background-color: #ffffff; border: 1px solid #e2e8f0; border-radius: 8px; max-width: 580px; margin: 0 auto; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05); overflow: hidden; }
        .header { background-color: #2f2a27; color: #f5f1e8; padding: 24px; text-align: center; }
        .header h2 { margin: 0; font-size: 1.5rem; letter-spacing: 0.5px; }
        .content { padding: 32px 24px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        td { padding: 12px 8px; border-bottom: 1px solid #f1f5f9; font-size: 0.95rem; vertical-align: top; }
        td.label { font-weight: bold; width: 35%; color: #64748b; }
        td.value { color: #0f172a; }
        .footer { background-color: #f1f5f9; padding: 16px; text-align: center; font-size: 0.8rem; color: #94a3b8; border-top: 1px solid #e2e8f0; }
      </style>
    </head>
    <body>
      <div class="wrapper">
        <div class="card">
          <div class="header">
            <h2>Hero Homes Lead Notification</h2>
          </div>
          <div class="content">
            <table>
              <tr><td class="label">Name:</td><td class="value">${lead.name}</td></tr>
              <tr><td class="label">Phone:</td><td class="value"><a href="tel:${lead.phone}">${lead.phone}</a></td></tr>
              <tr><td class="label">Email:</td><td class="value">${lead.email || 'N/A'}</td></tr>
              <tr><td class="label">Project:</td><td class="value">${lead.project_name || 'Hero Homes Greater Noida'}</td></tr>
              <tr><td class="label">Configuration:</td><td class="value">${lead.config || 'All Sizes'}</td></tr>
              <tr><td class="label">Message:</td><td class="value">${lead.message || 'N/A'}</td></tr>
              <tr><td class="label">Form Source:</td><td class="value">${lead.source || 'N/A'}</td></tr>
              <tr><td class="label">Source URL:</td><td class="value"><a href="${lead.source_url}">${lead.source_url}</a></td></tr>
              <tr><td class="label">UTM Tracking:</td><td class="value">${utmString}</td></tr>
              <tr><td class="label">Timestamp:</td><td class="value">${lead.timestamp || new Date().toISOString()}</td></tr>
            </table>
          </div>
          <div class="footer">
            &copy; 2026 Hero Homes Lead System. Generated by Cloudflare Pages.
          </div>
        </div>
      </div>
    </body>
    </html>
  `;

  try {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: `Hero Homes Leads <${fromEmail}>`,
        to: toEmail,
        subject: `New Lead: ${lead.name} - ${lead.source || 'Hero Homes'}`,
        html: htmlContent,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Resend API HTTP error ${response.status}: ${errorText}`);
    }

    const resData = await response.json();
    return { success: true, messageId: resData.id };
  } catch (err) {
    console.error('[Email Helper] Failed to send email via Resend:', err);
    return { success: false, error: err.message || 'Unknown email transmission error.' };
  }
}
